### PR TITLE
Upgrade Katana to 1.2.2

### PR DESCRIPTION
**Pull request by svenjacobs**
In addition to Katana 1.2.0 I migrated the project to AndroidX.

### CODE REVIEW

**Comment by Sloy** [comment]
Hi! Thanks for the update :)
I tested with one of the slower devices and Katana 1.2.0 seems to be twice as slow. Is that an expected behaviour?

Huawei hwALE-H with Android 6.0

Before:

Library | Setup Kotlin | Setup Java | Inject Kotlin | Inject Java
--- | ---:| ---:| ---:| ---:
**Koin** | 46,78 ms | 48,17 ms  | 2,40 ms | 2,37 ms
**Kodein** | 66,75 ms | 66,30 ms  | 8,07 ms | 7,66 ms
**Katana** | 11,06 ms | 11,41 ms  | 1,98 ms | 1,97 ms
**Custom** | 4,40 ms | 4,38 ms  | 0,64 ms | 0,79 ms
**Dagger** | 0,02 ms | 0,02 ms  | 0,23 ms | 0,20 ms

After:

Library | Setup Kotlin | Setup Java | Inject Kotlin | Inject Java
--- | ---:| ---:| ---:| ---:
**Koin** | 45,95 ms | 46,85 ms  | 2,29 ms | 2,27 ms
**Kodein** | 64,75 ms | 64,74 ms  | 7,56 ms | 7,57 ms
**Katana** | 25,60 ms | 26,84 ms  | 2,25 ms | 2,30 ms
**Custom** | 4,44 ms | 4,43 ms  | 0,65 ms | 0,80 ms
**Dagger** | 0,01 ms | 0,01 ms  | 0,23 ms | 0,20 ms

**Comment by svenjacobs** [comment]
Hi @Sloy, thanks for the quick feedback! :)

Can you please comment out this line

```kotlin
Katana.environmentContext = AndroidEnvironmentContext
```

and see if it improves performance?

In Katana 1.2.0 I improved memory usage on Android with the new `AndroidEnvironmentContext`. If this context is applied then an `ArrayMap` is used internally instead of a `HashMap`. However it could be that this collection - although more memory efficient - is also slower.

**Comment by svenjacobs** [comment]
By the way with my [speed comparison](https://github.com/rewe-digital-incubator/katana/tree/master/speed-comparison) I did not see any significant speed deterioration after this change. However here only Katana's core functionality is tested and not the Android extensions.

**Comment by Sloy** [comment]
Yes, when I remove that line the times go down as the previous version.
According to the [ArrayMap docs](https://developer.android.com/reference/android/util/ArrayMap), it's slower with large number of items. So I guess the performance impact will be greater with more dependencies.

**Comment by svenjacobs** [comment]
Yes, that's what I thought. But the documentation also states:

```
For containers holding up to hundreds of items, the performance difference is not significant, less than 50%
```

so I guess it depends on the use case. In your comparison you build a quite huge dependency graph so the impact is worse. I'm going to tweak this in Katana 1.2.1. Stay tuned :)

**Comment by svenjacobs** [comment]
I updated the PR. Please have a look.

**Comment by svenjacobs** [comment]
Further improved injection performance in Katana 1.2.2

**Comment by svenjacobs** [comment]
Hi @Sloy, I hope you had a nice holiday season. Any news on this PR? ;)

**Comment by Sloy** [comment]
Hi @svenjacobs, you too :) 
I'm still catching up with work. About this PR, I'm not yet familiar with AndroidX (migration in an big app is painful for sure), but this project is small enough that I don't see a reason not accept it.

I'll merge this now, and I'll try to find some time tomorrow (aprox) to pass the benchmark in our test devices and update the readme.

Thanks for the contributions!

**Pull request merged**
